In [14]:
import numpy as np

In [15]:
y_pred = np.random.choice([0, 1, 2], size=1000)
y_pred

array([1, 1, 0, 1, 0, 2, 2, 1, 2, 1, 2, 1, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2,
       1, 1, 2, 0, 0, 2, 2, 1, 2, 1, 2, 0, 2, 0, 0, 1, 2, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 2, 1, 0, 1, 0, 0, 2, 2, 0, 1, 2, 1, 2, 1, 0, 0,
       0, 2, 2, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 2, 2, 2, 1, 2, 0, 2,
       2, 1, 2, 0, 1, 0, 1, 2, 0, 1, 1, 0, 2, 0, 1, 0, 1, 1, 0, 2, 2, 2,
       0, 2, 0, 2, 0, 0, 1, 1, 0, 0, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0,
       1, 1, 2, 1, 0, 2, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 2, 2, 2, 0, 2, 2,
       1, 2, 2, 0, 2, 0, 2, 0, 1, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 0, 0, 2,
       2, 1, 2, 2, 0, 0, 1, 1, 2, 2, 2, 1, 0, 1, 1, 1, 0, 2, 1, 1, 1, 0,
       2, 2, 0, 0, 2, 2, 1, 2, 2, 0, 1, 0, 0, 0, 1, 1, 2, 0, 2, 2, 2, 2,
       1, 1, 0, 2, 1, 1, 0, 1, 0, 2, 0, 2, 0, 2, 0, 2, 2, 2, 1, 2, 2, 2,
       2, 1, 0, 2, 0, 1, 1, 0, 1, 1, 0, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0,
       2, 0, 2, 2, 0, 0, 1, 2, 1, 2, 0, 1, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2,
       2, 0, 2, 0, 1, 1, 1, 2, 2, 2, 2, 1, 1, 0, 0,

In [16]:
y = np.random.choice([0, 1, 2], size=1000)
y

array([1, 0, 0, 1, 0, 0, 0, 2, 2, 2, 1, 1, 2, 0, 0, 2, 2, 0, 2, 1, 0, 1,
       0, 2, 0, 0, 1, 1, 1, 1, 2, 0, 1, 2, 0, 2, 2, 2, 2, 1, 1, 1, 0, 2,
       2, 0, 2, 2, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 2, 1, 0, 1, 2, 2, 0, 0,
       0, 1, 2, 1, 2, 2, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 1, 1, 0, 2, 1,
       2, 0, 0, 2, 1, 1, 0, 2, 2, 0, 1, 2, 2, 2, 1, 1, 1, 1, 0, 1, 0, 1,
       2, 1, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 2, 1, 0, 1, 1, 0, 1, 2, 1, 2,
       2, 2, 2, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 2, 2, 2, 2, 2, 0, 1, 2, 2,
       0, 0, 2, 0, 0, 0, 0, 1, 0, 1, 2, 1, 2, 0, 1, 2, 1, 1, 0, 2, 1, 0,
       1, 0, 0, 1, 0, 1, 2, 0, 1, 2, 2, 2, 1, 2, 0, 1, 1, 0, 1, 2, 2, 0,
       1, 0, 2, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2, 0, 1, 0, 1, 2, 2, 2, 2, 1,
       1, 2, 1, 2, 0, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 0, 1, 0, 1,
       1, 2, 2, 1, 2, 0, 2, 2, 0, 0, 1, 2, 0, 2, 2, 1, 2, 1, 0, 2, 2, 2,
       2, 2, 0, 1, 1, 1, 0, 2, 1, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 2,
       0, 0, 2, 0, 1, 1, 2, 2, 2, 1, 2, 0, 2, 2, 1,

In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_pred)

array([[ 94,  89, 112],
       [100, 107, 115],
       [127, 122, 134]], dtype=int64)

In [18]:
cf = np.zeros((3, 3))
n_calss = 3
for yi, yhat in zip(y, y_pred):
    for i in range(n_calss):
        for j in range(n_calss):
            if yi == i and yhat == j:
                cf[i, j] += 1

print(cf)

[[ 94.  89. 112.]
 [100. 107. 115.]
 [127. 122. 134.]]


In [19]:
np.unique(y)
encoded_labels = ['a', 'b', 'c']
encoded_labels.index('b')

1

In [20]:
distances = [[0.5, 0.6, 6], [100, 10, 6], [4, 0, 2], [0.5, 5, 6], [10, 5, 2], [1, 8, 4], [0, 0.8, 800]]
distances.sort(key=lambda distances: distances[1])
distances

[[4, 0, 2],
 [0.5, 0.6, 6],
 [0, 0.8, 800],
 [0.5, 5, 6],
 [10, 5, 2],
 [1, 8, 4],
 [100, 10, 6]]

In [21]:
from Knn import Knn
import pandas as pd
from sklearn.model_selection import train_test_split
from labelEncoder import labelEncoder

In [22]:
data = np.array(pd.read_csv('./datasets/bezdekIris.data', header=None))

In [23]:
X = data[:, :4]
y = data[:, 4]
le = labelEncoder()
y = le.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [24]:
model = Knn()
model.train(X_train, y_train)
y_pred = model.predict(X_test)
scores = model.evaluate(X_test, y_test)
scores

{'mean_accuracy': 0.9833333333333333,
 'mean_precision': 0.9814814814814815,
 'mean_recall': 0.9833333333333334,
 'mean_F1-score': 0.981929181929182,
 'Confusion_matrix': array([[23,  0,  0],
        [ 0, 19,  0],
        [ 0,  1, 17]], dtype=int64)}

In [25]:
def cv_knn(N_split, X_train, y_train, X_test, y_test, K_values):

    X = np.concatenate((X_train, X_test), axis=0)
    y = np.concatenate((y_train, y_test), axis=0)

    # Splits
    X_splits = np.split(X, N_split)
    y_splits = np.split(y, N_split)

    # Recherche
    scores = {}
    for K in K_values:
        accuracys = []
        for i in range(N_split):
            X_train = np.concatenate(np.delete(X_splits, i, 0))
            X_test = X_splits[i]
            y_train = np.concatenate(np.delete(y_splits, i, 0))
            y_test = y_splits[i]

            model = Knn(K=K)
            model.train(X_train, y_train)
            acc = model.evaluate(X_test, y_test)['mean_accuracy']
            
            accuracys.append(acc)

        scores[K] = np.mean(accuracys)

    # print + selection
    print(max(scores.items(), key=operator.itemgetter(1)))
    return max(scores.items(), key=operator.itemgetter(1))[0]

In [13]:
import operator
from load_datasets import load_iris_dataset
from load_datasets import load_wine_dataset
from load_datasets import load_abalone_dataset

# Initialisez vos paramètres
K_values = [k for k in range(1, 10)]

# Charger/lire les datasets
X_train_iris, y_train_iris, X_test_iris, y_test_iris = load_iris_dataset(train_ratio=0.7, seed=42, shuffle=True)
X_train_wine, y_train_wine, X_test_wine, y_test_wine = load_wine_dataset(train_ratio=0.7, seed=42, shuffle=True)
X_train_abalone, y_train_abalone, X_test_abalone, y_test_abalone = load_abalone_dataset(train_ratio=0.7, seed=42, shuffle=True)

# Encode Iris y
le = labelEncoder()
y_train_iris = le.fit_transform(y_train_iris)
y_test_iris = le.transform(y_test_iris)

# Validation croisée
N_split_iris = 6 # --> Pas toutes les classes das les splits si > 6
N_split_wine = 3 # --> Trop long
N_split_abalone = 3 # --> Trop long

print('IRIS')
K_opti_iris = cv_knn(N_split_iris, X_train_iris, y_train_iris, X_test_iris, y_test_iris, K_values)
print('WIN')
K_opti_wine = cv_knn(N_split_wine, X_train_wine, y_train_wine, X_test_wine, y_test_wine, K_values)
print('ABALONE')
K_opti_abalone = cv_knn(N_split_abalone, X_train_abalone, y_train_abalone, X_test_abalone, y_test_abalone, K_values)

IRIS
(4, 0.98)
WIN
c:\Users\hk3pz\Documents\Cours\LAVAL\Hiver_2021\IFT_7025\TP2\Knn.py:81: RuntimeWarning: invalid value encountered in longlong_scalars
  self.precisions.append(row[i] / np.sum(row))
c:\Users\hk3pz\Documents\Cours\LAVAL\Hiver_2021\IFT_7025\TP2\Knn.py:87: RuntimeWarning: invalid value encountered in longlong_scalars
  self.recalls.append(row[i] / np.sum(row))


KeyboardInterrupt: 

In [31]:
x1 = np.array([1, 2, 5])
x2 = np.array([0, 5, 8])

(((x1 - x2)**2).sum())**0.5

4.358898943540674