In [1]:
import numpy as np

In [2]:
y_pred = np.random.choice([0, 1, 2], size=1000)
y_pred

array([1, 0, 0, 1, 0, 1, 1, 0, 2, 2, 2, 0, 2, 1, 2, 1, 1, 0, 0, 0, 1, 2,
       0, 1, 1, 1, 1, 2, 2, 0, 1, 1, 1, 2, 0, 0, 2, 0, 2, 1, 0, 0, 1, 1,
       2, 2, 2, 0, 0, 2, 0, 1, 0, 1, 2, 0, 2, 0, 2, 0, 0, 2, 0, 1, 1, 2,
       0, 2, 1, 1, 0, 0, 0, 2, 2, 2, 0, 1, 1, 0, 2, 2, 2, 0, 2, 1, 1, 1,
       1, 1, 0, 2, 2, 1, 0, 2, 2, 2, 1, 2, 0, 2, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 2, 1, 1, 2, 1, 0, 2, 0, 0, 1, 0, 0, 1, 2, 2, 2, 0,
       2, 2, 2, 0, 1, 0, 1, 2, 2, 2, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 2, 0, 1, 0, 2, 2, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 2, 1, 2, 2, 1, 2, 2, 0, 0, 0, 2, 0, 1, 0,
       0, 2, 1, 0, 0, 1, 2, 1, 2, 0, 0, 1, 2, 0, 0, 1, 0, 1, 2, 1, 0, 2,
       2, 0, 1, 0, 1, 2, 0, 0, 0, 0, 2, 2, 1, 2, 1, 0, 0, 1, 2, 0, 1, 0,
       1, 0, 1, 0, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2, 0, 0, 2, 2, 0, 2,
       0, 1, 1, 2, 1, 1, 1, 1, 1, 0, 2, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 2, 1, 2, 2, 2, 0, 2, 0, 0, 2, 1, 2, 1, 1,

In [3]:
y = np.random.choice([0, 1, 2], size=1000)
y

array([2, 2, 0, 1, 2, 0, 2, 1, 2, 0, 1, 0, 1, 0, 0, 2, 1, 0, 1, 1, 1, 2,
       1, 1, 0, 0, 2, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       2, 0, 0, 1, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 1, 2, 2, 1,
       1, 0, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 0, 1,
       0, 1, 0, 0, 2, 0, 2, 1, 2, 0, 0, 1, 1, 0, 1, 0, 1, 2, 0, 1, 0, 2,
       1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 0, 2, 1, 0, 1, 2, 2, 0, 1, 2, 1,
       0, 0, 2, 0, 0, 1, 0, 2, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 2, 0, 1, 0, 0, 1, 2, 1, 1, 0, 1, 2, 0, 1, 2, 2, 0, 2, 0, 1, 1,
       1, 1, 0, 0, 2, 2, 0, 0, 2, 1, 2, 2, 0, 1, 2, 1, 0, 0, 2, 0, 0, 1,
       0, 0, 2, 0, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 1, 0, 2, 2, 2, 0, 0, 0,
       1, 0, 0, 2, 1, 2, 1, 0, 0, 1, 0, 1, 2, 1, 1, 0, 2, 0, 1, 0, 2, 1,
       1, 1, 2, 2, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 2, 0, 1, 0, 1, 2, 0, 0,
       0, 0, 2, 0, 1, 1, 1, 2, 1, 0, 0, 2, 0, 2, 0, 0, 0, 1, 1, 0, 2, 1,
       1, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 1, 2, 1, 0,

In [4]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_pred)

array([[123, 111, 106],
       [133, 105, 106],
       [110,  99, 107]], dtype=int64)

In [5]:
cf = np.zeros((3, 3))
n_calss = 3
for yi, yhat in zip(y, y_pred):
    for i in range(n_calss):
        for j in range(n_calss):
            if yi == i and yhat == j:
                cf[i, j] += 1

print(cf)

[[123. 111. 106.]
 [133. 105. 106.]
 [110.  99. 107.]]


In [6]:
np.unique(y)
encoded_labels = ['a', 'b', 'c']
encoded_labels.index('b')

1

In [7]:
distances = [[0.5, 0.6, 6], [100, 10, 6], [4, 0, 2], [0.5, 5, 6], [10, 5, 2], [1, 8, 4], [0, 0.8, 800]]
distances.sort(key=lambda distances: distances[1])
distances

[[4, 0, 2],
 [0.5, 0.6, 6],
 [0, 0.8, 800],
 [0.5, 5, 6],
 [10, 5, 2],
 [1, 8, 4],
 [100, 10, 6]]

In [8]:
from Knn import Knn
import pandas as pd
from sklearn.model_selection import train_test_split
from labelEncoder import labelEncoder

In [9]:
data = np.array(pd.read_csv('./datasets/bezdekIris.data', header=None))

In [10]:
X = data[:, :4]
y = data[:, 4]
le = labelEncoder()
y = le.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [11]:
model = Knn()
model.train(X_train, y_train)
y_pred = model.predict(X_test)
scores = model.evaluate(X_test, y_test)
scores

{'mean accuracy': 0.9666666666666667,
 'mean precision': 0.9639376218323585,
 'mean recall': 0.9639376218323585,
 'mean F1-score': 0.9639376218323585,
 'Confusion_matrix': array([[23,  0,  0],
        [ 0, 18,  1],
        [ 0,  1, 17]], dtype=int64)}

In [14]:
le.inverse_transform(y)


array([], dtype=float64)