In [1]:
import numpy as np

In [2]:
y_pred = np.random.choice([0, 1, 2], size=1000)
y_pred

array([0, 0, 2, 2, 1, 1, 0, 2, 1, 2, 0, 2, 1, 2, 0, 1, 1, 0, 1, 1, 0, 0,
       2, 0, 1, 2, 2, 2, 0, 0, 2, 1, 2, 0, 0, 1, 1, 0, 0, 1, 2, 1, 2, 1,
       1, 2, 1, 1, 1, 0, 0, 0, 0, 1, 0, 2, 0, 2, 1, 0, 2, 0, 1, 1, 2, 0,
       2, 2, 1, 2, 2, 2, 0, 1, 1, 2, 0, 0, 2, 0, 0, 0, 2, 2, 0, 1, 2, 2,
       0, 1, 2, 2, 2, 0, 2, 1, 0, 1, 0, 1, 1, 2, 2, 2, 2, 0, 0, 0, 2, 2,
       1, 0, 2, 0, 2, 1, 2, 1, 2, 2, 1, 2, 2, 0, 0, 0, 2, 1, 2, 2, 1, 1,
       0, 2, 2, 0, 0, 2, 2, 1, 2, 2, 0, 2, 0, 0, 1, 1, 2, 2, 2, 0, 2, 2,
       2, 0, 1, 0, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1,
       0, 1, 0, 0, 1, 1, 2, 1, 0, 0, 1, 0, 0, 1, 2, 1, 2, 1, 1, 2, 0, 2,
       1, 0, 0, 2, 0, 2, 1, 0, 0, 1, 1, 0, 1, 1, 1, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 1, 2, 1, 1, 0, 2, 2, 1, 0, 0, 2, 1, 1, 1, 0, 1, 0, 2, 1, 1,
       2, 2, 0, 0, 2, 1, 0, 2, 1, 2, 2, 1, 0, 2, 2, 2, 0, 0, 1, 2, 1, 2,
       0, 0, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0, 0, 0, 1, 0, 2, 2, 2, 2,
       2, 1, 0, 0, 1, 0, 2, 0, 1, 0, 1, 0, 2, 0, 2,

In [3]:
y = np.random.choice([0, 1, 2], size=1000)
y

array([0, 1, 1, 1, 1, 2, 0, 1, 2, 0, 1, 2, 2, 0, 2, 0, 2, 0, 0, 2, 1, 1,
       0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 1, 0, 1, 0, 0, 2, 0, 2, 2, 0,
       1, 2, 2, 2, 2, 1, 0, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 0,
       2, 1, 0, 1, 1, 0, 1, 0, 2, 2, 1, 0, 0, 2, 0, 0, 1, 2, 1, 1, 0, 1,
       0, 2, 1, 1, 0, 2, 1, 2, 0, 2, 1, 0, 0, 2, 1, 0, 0, 2, 2, 0, 0, 2,
       2, 1, 2, 2, 2, 0, 2, 0, 1, 1, 0, 0, 2, 2, 1, 0, 1, 1, 0, 1, 2, 1,
       0, 0, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 0, 2, 2, 2, 0, 2, 0, 0, 0, 0,
       0, 2, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 2, 0, 0,
       1, 2, 1, 1, 2, 2, 1, 2, 1, 0, 2, 1, 0, 2, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 2, 2, 0, 1, 1, 1, 0, 2, 0, 0, 1, 1, 1, 2, 0, 2, 0, 2, 2, 2, 1,
       2, 1, 1, 1, 2, 0, 1, 2, 0, 0, 2, 1, 2, 2, 1, 2, 2, 0, 2, 1, 2, 0,
       1, 0, 2, 0, 0, 2, 2, 0, 2, 2, 0, 1, 2, 1, 2, 1, 0, 2, 2, 0, 0, 0,
       0, 1, 2, 1, 1, 1, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 2,
       0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0,

In [4]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_pred)

array([[119, 103, 123],
       [138,  92, 108],
       [105, 104, 108]], dtype=int64)

In [5]:
cf = np.zeros((3, 3))
n_calss = 3
for yi, yhat in zip(y, y_pred):
    for i in range(n_calss):
        for j in range(n_calss):
            if yi == i and yhat == j:
                cf[i, j] += 1

print(cf)

[[119. 103. 123.]
 [138.  92. 108.]
 [105. 104. 108.]]


In [6]:
np.unique(y)
encoded_labels = ['a', 'b', 'c']
encoded_labels.index('b')

1

In [7]:
distances = [[0.5, 0.6, 6], [100, 10, 6], [4, 0, 2], [0.5, 5, 6], [10, 5, 2], [1, 8, 4], [0, 0.8, 800]]
distances.sort(key=lambda distances: distances[1])
distances

[[4, 0, 2],
 [0.5, 0.6, 6],
 [0, 0.8, 800],
 [0.5, 5, 6],
 [10, 5, 2],
 [1, 8, 4],
 [100, 10, 6]]

In [8]:
from Knn import Knn
import pandas as pd
from sklearn.model_selection import train_test_split
from labelEncoder import labelEncoder

In [9]:
data = np.array(pd.read_csv('./datasets/bezdekIris.data', header=None))

In [10]:
X = data[:, :4]
y = data[:, 4]
le = labelEncoder()
y = le.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [11]:
model = Knn()
model.train(X_train, y_train)
y_pred = model.predict(X_test)
scores = model.evaluate(X_test, y_test)
scores

{'mean accuracy': 0.9666666666666667,
 'mean precision': 0.9639376218323585,
 'mean recall': 0.9639376218323585,
 'mean F1-score': 0.9639376218323585,
 'Confusion_matrix': array([[23,  0,  0],
        [ 0, 18,  1],
        [ 0,  1, 17]], dtype=int64)}

In [55]:
X, y = [], []
sexes = {'M': 0, 'F': 1, 'I': 2}
with open('datasets/abalone-intervalles.csv', 'r') as f:
    for line in f:
        line = line.rstrip().split(',')
        line[0] = sexes[line[0]]
        line[8] = float(line[8])
        X.append(line[:8])
        y.append(line[8])
f.close()
X = np.array(X, dtype='float64')
y = np.array(y, dtype='int64')

In [56]:
X

array([[0.    , 0.455 , 0.365 , ..., 0.2245, 0.101 , 0.15  ],
       [0.    , 0.35  , 0.265 , ..., 0.0995, 0.0485, 0.07  ],
       [1.    , 0.53  , 0.42  , ..., 0.2565, 0.1415, 0.21  ],
       ...,
       [0.    , 0.6   , 0.475 , ..., 0.5255, 0.2875, 0.308 ],
       [1.    , 0.625 , 0.485 , ..., 0.531 , 0.261 , 0.296 ],
       [0.    , 0.71  , 0.555 , ..., 0.9455, 0.3765, 0.495 ]])

In [57]:
y

array([2, 1, 1, ..., 1, 1, 1], dtype=int64)

In [13]:
import random

def train_test_split(X, y, test_size=0.3, seed=69, shuffle=True):
    assert len(X) == len(y)
    
    if shuffle:
        random.seed(seed)
        random.shuffle(X)
        random.shuffle(y)
    
    X_train = X[:int((len(X)+1)*(1-test_size))]
    X_test = X[int((len(X)+1)*(1-test_size)):]

    y_train = y[:int((len(y)+1)*(1-test_size))]
    y_test = y[int((len(y)+1)*(1-test_size)):]


    return X_train, X_test, y_train, y_test